name: CI

on:
  - push
  - pull_request
#paths-ignore:
#    - '**.md'

jobs:
  lint:
    name: ${{ matrix.command }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Run lint
        run: yarn && yarn lint
        env:
          CI: true

  test:
    name: ${{ matrix.command }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Run test
        run: yarn && yarn build && yarn test
        env:
          CI: true